name: generate badges

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */8 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    - main
    - output
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
     - name: Detailed display
       uses: lowlighter/metrics@latest
       with:
         filename: metrics.plugin.achievements.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_achievements: yes
         plugin_achievements_only: sponsor, maintainer, octonaut
     - name: Compact display
       uses: lowlighter/metrics@latest
       with:
         filename: metrics.plugin.achievements.compact.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_achievements: yes
         plugin_achievements_only: >-
          polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          scripter, packager, explorer, infographile, manager
         plugin_achievements_display: compact
         plugin_achievements_threshold: X
     - name: Gists
       uses: lowlighter/metrics@latest
       with:
         filename: metrics.plugin.gists.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_gists: yes
     - name: Licenses with open-source ratio graphs
       uses: lowlighter/metrics@latest
       with:
        filename: metrics.plugin.licenses.ratio.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        template: repository
        repo: arkapg211002
        plugin_licenses: yes
        plugin_licenses_setup: npm ci
        plugin_licenses_legal: no
        plugin_licenses_ratio: yes
     - name: Indepth analysis
       uses: lowlighter/metrics@latest
       with:
        filename: metrics.plugin.notable.indepth.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_notable: yes
        plugin_notable_indepth: yes
        plugin_notable_repositories: yes
     - name: Favorites anime and currently watching
       uses: lowlighter/metrics@latest
       with:
        filename: metrics.plugin.anilist.svg
        token: NOT_NEEDED
        base: ""
        plugin_anilist: yes
        plugin_anilist_medias: anime
        plugin_anilist_sections: favorites, watching
        plugin_anilist_limit: 1
     





    
