name: Active-project

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Main Workflow 
    steps:
      - name: Project from a repository
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugin_projects_descriptions: yes
