name: habits

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */8 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    - main
    - output
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
     - name: Recent activity charts
       uses: lowlighter/metrics@latest
       with:
         filename: metrics.plugin.habits.charts.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_habits: yes
         plugin_habits_facts: no
         plugin_habits_charts: yes
         config_timezone: Europe/Paris
     - name: Midly interesting facts
       uses: lowlighter/metrics@latest
       with:
         filename: metrics.plugin.habits.facts.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_habits: yes
         plugin_habits_facts: yes
         plugin_habits_charts: no
         config_timezone: Europe/Paris

