name: recent stars

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */8 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    - main
    - output
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
     - name: Recently starred
       uses: lowlighter/metrics@latest
       with:
        filename: metrics.plugin.stars.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_stars: yes
        plugin_stars_limit: 3
