name: skyline graph

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */8 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    - main
    - output
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
     - name: GitHub Skyline
       uses: lowlighter/metrics@latest
       with:
        filename: metrics.plugin.skyline.svg
        token: NOT_NEEDED
        base: ""
        plugin_skyline: yes
        plugin_skyline_year: 2022
        plugin_skyline_frames: 120
        plugin_skyline_quality: 1
