name: Code-snippet

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Main Workflow 
    steps:
       - name: JavaScript or TypeScript snippet of the day
         uses: lowlighter/metrics@latest
         with:
            filename: metrics.plugin.code.svg
            token: ${{ secrets.GITHUB_TOKEN }}
            base: ""
            plugin_code: yes
            plugin_code_languages: java, C
            plugin_code_load: 400
