name: Wakatime

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Main Workflow 
    steps:
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements2.compact.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
             polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
             scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
      
